export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const SET_NEWS_TABLE_FIELDS = 'SET_NEWS_TABLE_FIELDS';
export const SET_NEWS_TABLE_DATA = 'SET_NEWS_TABLE_DATA';
