export const FETCH_COMPETITIONS_REQUEST = 'FETCH_COMPETITIONS_REQUEST';
export const FETCH_COMPETITIONS_FAILURE = 'FETCH_COMPETITIONS_FAILURE';
export const FETCH_COMPETITIONS_SUCCESS = 'FETCH_COMPETITIONS_SUCCESS';

export const FETCH_COMPETITION_SECTIONS_REQUEST = 'FETCH_COMPETITION_SECTIONS_REQUEST';
export const FETCH_COMPETITION_SECTIONS_FAILURE = 'FETCH_COMPETITION_SECTIONS_FAILURE';
export const FETCH_COMPETITION_SECTIONS_SUCCESS = 'FETCH_COMPETITION_SECTIONS_SUCCESS';
