export const FETCH_COMPETITIONS_REQUEST = 'FETCH_COMPETITIONS_REQUEST';
export const FETCH_COMPETITIONS_FAILURE = 'FETCH_COMPETITIONS_FAILURE';
export const FETCH_COMPETITIONS_SUCCESS = 'FETCH_COMPETITIONS_SUCCESS';
